---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-api-database
  name: currency-api-database

spec:
  ports:
    - name: currency-api-database-port
      port: 5432
      protocol: TCP
      targetPort: 5432
  type: ClusterIP
  selector:
    app: currency-api-database
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: currency-api
spec:
  updateStrategy:
    type: RollingUpdate

  selector:
    matchLabels:
      app: currency-api-database
      type: currency-api-database

  serviceName: currency-api
  replicas: 1
  template:
    metadata:
      labels:
        app: currency-api-database
        type: currency-api-database
    spec:
      terminationGracePeriodSeconds: 10

      containers:
        - name: currency-api
          image: postgres:13.3
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password

            - name: POD_IP
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.podIP

          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
              subPath: postgres-db


  volumeClaimTemplates:
    - metadata:
        name: postgres
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 3Gi