apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: currency-api-ingress
spec:
  rules:
    - host: currency-api.com
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: currency-api
                port:
                  number: 80